apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab
secretGenerator:
- name: registry-auth-cert
  files:
  - registry-auth.crt
  - registry-auth.key
  - dhparam.pem
generatorOptions:
  disableNameSuffixHash: true
