apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: docker-registry
  name: docker-registry-config
  namespace: gitlab
data:
  config.yml: |-
    version: 0.1
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    http:
      addr: :5000
      headers:
        X-Content-Type-Options:
        - nosniff
    log:
      level: info
      fields:
        service: registry
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
      cache:
        blobdescriptor: redis
    redis:
      addr: redis-svc:6379    
---
apiVersion: v1
data:
  haSharedSecret: U29tZVZlcnlTdHJpbmdTZWNyZXQK
kind: Secret
metadata:
  labels:
    app: docker-registry
    chart: docker-registry-1.4.3
  name: docker-registry-secret
  namespace: gitlab
type: Opaque
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: docker-registry
  namespace: gitlab
spec:
  selector:
    matchLabels:
      app: docker-registry
  serviceName: "docker-registry-svc"
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - command:
        - /bin/registry
        - serve
        - /etc/docker/registry/config.yml
        env:
        - name: REGISTRY_HTTP_SECRET
          valueFrom:
            secretKeyRef:
              key: haSharedSecret
              name: docker-registry-secret
        # - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
        #   value: /var/lib/registry
        # - name: REGISTRY_STORAGE_DELETE_ENABLED
        #   value: "true"
        - name: REGISTRY_AUTH_TOKEN_REALM
          value: https://gitlab.dev.lan/jwt/auth
        - name: REGISTRY_AUTH_TOKEN_SERVICE
          value: container_registry
        - name: REGISTRY_AUTH_TOKEN_ISSUER
          value: gitlab-issuer
        - name: REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE
          value: /certs/ca.crt
        image: registry:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: docker-registry
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/registry/
          name: data
        - mountPath: /etc/docker/registry
          name: docker-registry-config
        - mountPath: /certs
          name: auth-cert
          #readOnly: true
      volumes:
      - name: auth-cert
        secret:
          secretName: gitlab-home-tls
      - name: docker-registry-config
        configMap:
          name: docker-registry-config
        
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-registry
  name: docker-registry-svc
  namespace: gitlab
spec:
  #externalTrafficPolicy: Cluster
  ports:
  - name: registry
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: docker-registry
  sessionAffinity: None
  type: ClusterIP